# Introduction to Python for Medical Imaging

## 1.1 Brief introduction to Jupyter Notebooks
In Jupyter notebook, we have an installed version of Python on our local machine...
Can create new cells for writing information known as "markdown", or "code" for step-by-step programming

In [10]:
import pydicom as pyd
import numpy as np

### Keywords
When naming variables or functions, there are many options. However, there are specific **keywords** that are recognized with a programmatic meaning and will (depending on your IDE or programming space) be differentiated by a different color <br>
Common keywords include: **for, while, if, elif, else, in, is, None, def, import, ...**<br>
Types are similar to keywords such that they are recognized with different meaning: **int, float, str, list, typle, ...**<br>
Compared to other programming languages, reading Python is close to reading English <br>

In [12]:
name = 'Ronald'
coding_experience = None
if coding_experience is None:
    print('Ron is new to programming')

Ron is new to programming


### Commenting
We can comment in our out a section by using ctrl + /

In [1]:
# We can either comment using a hashtag
"""
or multiline comment 
by using triple quotes on either side
"""
print('We can comment out the rest of a line')  # COMMENT ON SAME LINE

We can comment out the rest of a line


### Built-in Functions
These functions are built-in from Python and going to be everywhere. We don't need to understand them in depth yet, moreso that whenever you see these being called, you'll know what they are!

In [26]:
print('We love print')

We love print


In [35]:
str1 = 'our string'
str_size = len(str1)
print('len returns the length or size of the object. For a str, its the # of character', str_size)

len returns the length or size of the object. For a str, its the # of character 10


In [36]:
ls = range(str_size) 
print('range creates a list of numbers based on inputs. In this case ls =', ls[0], ls[1], ls[2], '...', ls[-2], ls[-1])

range creates a list of numbers based on inputs. In this case ls = 0 1 2 ... 8 9


In [39]:
maximum = max(30, -12, 28)          # We can give it n-arguments of numbers
ls = [30, -12, 28]
minimum = min(ls)                   # We can also give it a list of numbers
print(maximum)
print(minimum)

30
-12


### Strings

In [13]:
str1 = 'abc'         # Equivalently, we can use "" in Python. There is no 'character' data type  
str2 = ''            # empty string
print(str1)
print(str2)          # will print an empty string
print(len(str1))     # built in function len() returns the size of an object
     

abc

3


In [40]:
str3 = str(67)       # Type casting: from integer to string
str4 = str3 + '41'   # string addition concatenates them one after the other
print(str4)
print(str1[0])    

6741
o


In [41]:
# Special characters \n, \t, etc. \n is for 'newline', \t is for 'tab'
print('1st line\n\t2nd line with tabbing')

1st line
	2nd line with tabbing


In [42]:
# an 'r' before the string quotation marks reads with no special characters
main_dir = r'C:\Users\ddesarn\Downloads\Danny'   # The \U will throw an exception if we don't have r before the string!
print(main_dir)

C:\Users\ddesarn\Downloads\Danny


### Integers and Floats

In [9]:
int1 = 3                # initialize an integer. Notice it initiliazed the type automatically
int2 = float('3')       # Type cast this string into a float number
print(type(int1))
print(int1+int2)        # an integer plus a float will return a float
print(type(int1+int2))

<class 'int'>
6.0
<class 'float'>


### Booleans and Conditionals

In [18]:
str1 = 'Run'
str2 = 'run'
if str1 == str2:  # '==' is a conditional. Conditionals return either True or False, which are booleans
    print('true!')
else:
    print(False)

False


In [16]:
bool1 = True
print(type(bool1))

<class 'bool'>


#### isinstance():
`isinstance()` is a common function to see if a variable has a type we are looking for. If the object has the type provided as input, then the function returns `True` and `False` otherwise. **Note** that this applies for everything that isn't a `None` type. See below how to check for `None`

In [111]:
ls = [1, 2, 3]
is_ls = isinstance(ls, list)   # note we put the type keyword as the second argumen
print(is_ls)

True


In [113]:
ele = None
if ele is None:                # this is how you check for None
    print('The trivial solution is the best solution')

The trivial solution is the best solution


In practice, if we need to check the types of variables in a function, we can set a default value of `None` and then lead with that for our `if` `elif` (short for "else if") and `else` statements

In [118]:
def check_types(ls):
    for ele in ls:
        if ele is None:
            print('this is None')
        elif isinstance(ele, tuple):
            print('this is in elif')
        else:
            print('this is in else')

ls = ['1', 2, (3, ), None]
check_types(ls)

this is in else
this is in else
this is in elif
this is None


### Lists

In [44]:
list1 = [23, '67', 'bob']      # a list can group objects of the same or different types and sizes together
print(list1)

[23, '67', 'bob']


**Indexing** is an important tool we use to access information from an object, like a list. Here, we have list1 which has 3 items, and so if I want to access the nth item, I would use the index (n-1) since indexing starts from 0 in Python. The 0th element of `list1[0]` is `23`, the 1st element `list[1]` is `'67'` and 2nd element `list[2]` is `'bob'`

To clarify brackets usage:<br>
`list1[]`   we are indexing through list1<br>
`list1()`   we are expecting list1 to be a function call<br>

In [45]:
list1[0] = list1[0] + 3        # edit the 0th element of our list and save it to the 0th position
print(list1)

[26, '67', 'bob']


**This is important: if a list is made of objects that we have saved somewhere, the list POINTS to that object. This means that if the object is changed, the list will be changed too!**

In [93]:
abc = [1, 2, 3]                 # list abc points to the number 1 saved at some location in memory
d = str('67676')
list1 = [abc, d]
print('list1 before:', list1)

abc[0] = 5
print('list1 after: ', list1)

list1 before: [[1, 2, 3], '67676']
list1 after:  [[5, 2, 3], '67676']


In [53]:
num = 5.0
list2 = [num, d]
print(list2)

num = num + 1                  # tricky: we are not updating num, we are doing a calculation and replacing the var num with the result
print(list2)

[5.0, '67676']
[5.0, '67676']


#### Iteration of a list:
Here, we will set up a **for loop** to look at the different elements of the list. There are different ways to do this:
1. We can loop through the elements directly by using an indexing variable name, for example `ele` (for element), the keyword `in` and our list
2. We can loop using an indexing variable of numbers that relate to indices in the list
3. We can loop using `enumerate`, to get both the indice and the element of our list

In [88]:
# 1.
for ele in list2:
    print(f'ele = {ele}')

ele = 5.0
ele = 67676


In [90]:
# 2.
for ii in range(len(list2)):
    print(f'ii = {ii}, and list2[ii] = {list2[ii]}')

ii = 0, and list2[ii] = 5.0
ii = 1, and list2[ii] = 67676


In [92]:
# 3.
for ii, ele in enumerate(list2):
    print(f'ii = {ii}, and ele = {ele}')

ii = 0, and ele = 5.0
ii = 1, and ele = 67676


### Tuples
Tuples behave almost exactly like lists, but the difference is that **lists are mutable** and **tuples are immutable**. That means that once we make a tuple, we cannot change it. Whereas a list, we can. Whereas for lists we use `[]`, for tuples we use `()`. 

In [107]:
tup = (1, 2, 'yes')
for ele in tup:
    print(ele)

1
2
yes


**Note** you can put any number in brackets and it won't form a tuple. By having numbers separated by a comma allows for a tuple. Meaning, if we want a tuple with one element we can use `(item, )`

In [110]:
num = (100 * 3 / 7) 
tup = (num, )
print(f'num is {num}, and has type {type(num)}')
print(f'tup is {tup}, and has type {type(tup)}')

num is 42.857142857142854, and has type <class 'float'>
tup is (42.857142857142854,), and has type <class 'tuple'>


### 2D List

Lists inside of other lists create *deeper* lists. Note, `list` is a recognized type, and so for naming a generic list `ls` is a better convention

In [81]:
list3 = [[1, 2], [3, 4]]         # a list with 2 rows, 2 columns

print(f'list3:                                      {list3}')
print(f'the 0th element of list3:                   {list3[0]}')
print(f'the 1st row, and 0th col element of list3:  {list3[1][0]}')
print(list4)

list3:                                      [[1, 2], [3, 4]]
the 0th element of list3:                   [1, 2]
the 1st row, and 0th col element of list3:  3
[[5, 6], [7, 8]]


In [82]:
list4 = [[5, 6],                 # list4 has the same shape as list3, but easier to understand!
         [7, 8]]
list_add = list3 + list4
print(f'adding list concatenates the lists rather than adding the elements!\n{list_add}')

adding list concatenates the lists rather than adding the elements!
[[1, 2], [3, 4], [5, 6], [7, 8]]


In [96]:
list5 = [[1, 2, 3],              # a list with 2 rows, 3 columns
         [4, 5, 6]]
print(f'length of list5:             len(list5) = {len(list5)}')
print(f'length of list5, 0th row:    len(list5[0]) = {len(list5[0])}')

length of list5:             len(list5) = 2
length of list5, 0th row:    len(list5[0]) = 3


#### Iteration through a 2D list:
Here we are going to use a **nested for loop**. This means, inside one `for` loop, we have another `for` loop. To do this, we will have two sets of indices to keep track of: `ii` for the **ith** element of the rows, and `jj` for the **jth** element of the columns.<br>

In this example, we want to iterate and adjust each element by one and return a 1D list:

In [100]:
list6 = []                              # initiate an empty list to fill with new values
for ii in range(len(list5)):
    for jj in range(len(list5[ii])):
        ele = list5[ii][jj] + 1
        list6.append(ele)               # .append() is a function for the list class 
    
print(list6)

[2, 3, 4, 5, 6, 7]


### Printing

In [11]:
print('we can put a string in here')
print('we can also print other types', 25)  # we can use a comma to separate print arguments

we can put a string in here
we can also print other types 25


#### F-strings (introduced in Python ver 3.6):
Formatted string literals or F-strings allow for easier printing. Use `{}` around your variable and an `f` before your string

In [63]:
name = 'Junior'
age = 20
print(f'{name} is a cute name for a {age} year old dog')

Junior is a cute name for a 20 year old dog


#### Old-Style String Formatting (printf-style):
An older style that has placeholders of certain types embedded in our string. 
- First, we embed the placeholders in our string:`%s` would be for a string, `%i` for integer, `%.3f` for a fraction with 3 decimal places, etc.
- Second, outside the string place a `%` followed by our input variable or a tuple of the variables
- If we have one variable to input, we don't need the brackects

In [65]:
print('%s is a cute name for a %.2f year old dog' % (name, age))

Junior is a cute name for a 20.00 year old dog


### Functions
For functions we use the keyword 'def' followed by a space, our function name, parenthesis, and inside those parenthesis are **input variables** or **parameters**. `test_fcn()` for example doesn't have any required input parameters and returns nothing

In [66]:
def test_fcn():                        # we define the function starting here
    print("What a time to be alive")
    return

test_fcn()                             # we now call the function

What a time to be alive


`test_fcn2()` has three different inputs, but notice that we have given a **default** value to the parameter `is_dog`. Other details to note:
- We don't need to have a `return`
- We can have a **docstring** by having a `""" """` comment immediately after the `def fcn():` line
- When you mouse over any function in an IDE (for example, PyCharm), it will provide info of the function as described in the docstring
- We can use the `@param var_name:` in a docstring to highlight info for each input variable

In [68]:
def test_fcn2(name, age, is_dog=True):
    """
    @param name: name of the individual
    @param age: age of the individual in years
    @param is_dog: default value is True, and describes whether the individual input is a dog
    """
    if is_dog:
        print(f'{name} is {7*age} in dog years')
    else:
        print('I only care about dogs.')
        
name = 'Luna'
age = 3
test_fcn2(name, age)

Luna is 21 in dog years


`test_fcn3()` demonstrates that we can ask for a specific type of input, but we can give it a different input type without giving us an error upfront!

In [61]:
def test_fcn3(name: str, age: int):  # ask for a specific kind of input
    print(name, age)
    
age = 3.0                            # update age to a float number
test_fcn3(name, age)

Luna 3.0


### Memory
be carefuly with function calls~!

In [16]:
# Example 1: How does an item in a list get stored?
int1 = 67
print(id(int1))
list2 = [int1, int1+int1, 'straw']
print(id(list2[0]))
print(list2)
int1 = 100.0
print(id(int1))
print(list2)
print(id(list2))

140707607822840
140707607822840
[67, 134, 'straw']
1761574742608
[67, 134, 'straw']
1761575095040


In [ ]:
# Example 2: For loop and local variables
xx = 0
for ii in range(10):
    xx += 1
    yy = ii                            
print(xx)
# yy won't be saved outside of the loop in other languages, but in Python, it persists
print(yy)

In [19]:
# Example 3: Functions and scope
def test_ls(xx: int, ls: list):
    ls.append(xx)
    return ls

ls = []
xx = 10
ls2 = test_ls(xx, ls)
print(ls)
print(ls2)

[10]
[10]


In [24]:
def test_arr(xx: int, arr: np.ndarray):
    arr[0] = xx
    return arr

arr = np.zeros(1, dtype=int)
xx = 10
arr2 = test_arr(xx, arr)
print(arr)
print(arr2)

[10]
[10]


In [25]:
print(arr.dtype)
print(arr2.dtype)

int64
int64


### File searching
This may be the most important non-scientific topic we will go over. Understanding how to precisely select what we want in a simple way will pay dividends when we have many studies with different types of scans, file types, etc. <br>
Our savior is going to be a package called "glob" that is a Linux-style filesearching library. In the string we provide to `glob.glob`, each section of the string we want to fill in, we use a `*`.<br>
In the example below, imagine the directory I'm interested in has 100 DICOM images, each with a filename `im_0.dcm`, `im_1.dcm`, ..., `im_99.dcm` and for example, it is in every folder in `\Downloads`. Then the code below would return those 100 images for each folder all into one list.

In [120]:
import glob

fps = glob.glob(r'C:\Users\ddesarn\Downloads\**\im_*.dcm')     # filepaths = fps
print(fps)                                                  # can also use glob for a recurvsive file search using argument: recursive=True


[]


### NumPy
One of the main differences about writing good Python code involves learning to make use of NumPy instead of using for loops. This is because in Python, every variable is an object. Iterating using objects is slow in terms of loading the information and performing actions. This is in contrast to for example a for loop using integers in C++, where we are only loading in that 8bit number for example. NumPy takes what we want to do and does it using C++ variables and returns it. <br> 
Why would we do it this way? It is natural to write/read, turns loops into one liners, and is much faster than nested for loops (in Python)

In [ ]:
import numpy as np

#### Initialization
Many ways to initialize, here are the most common:

In [137]:
arr_from_ls = np.array([0, 3, 4, 6])           # We can type cast a list of the same types (we can also do lists of lists of same types!)
zeros = np.zeros((3, 5))                       # Here we are inputing the shape we want
ones = -256 * np.ones((2, 3, 3))
zeros_like = np.zeros_like(zeros)              # Note that it chooses the same type if you use np.zeros_like

print(arr_from_ls)
print(zeros)
print(ones)

[0 3 4 6]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[-256. -256. -256.]
  [-256. -256. -256.]
  [-256. -256. -256.]]

 [[-256. -256. -256.]
  [-256. -256. -256.]
  [-256. -256. -256.]]]


We can access different properties of a NumPy array, like .shape, ndim (number of dimensions)

In [139]:
print(f"the array 'ones' has {ones.ndim} dimensions and a shape {ones.shape}")

the array 'ones' has 3 dimensions and a shape (2, 3, 3)


In [124]:
bools = np.ones(10, dtype=bool)                # force the data type with dtype=type_keyword
print(bools)

[ True  True  True  True  True  True  True  True  True  True]


In [127]:
# arr = np.arange(10)                          # also works!
arr = np.arange(0, 10, 1)                      # arange(start, stop step): start at start, take n-number steps until start + n*step >= stop
print(arr)                                     # Note that stop is not included

arr1 = np.linspace(0, 10, 3, endpoint=True)    # linspace(start, stop, num): num is the number of equally spaced divisions.
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
[ 0.  5. 10.]


In [128]:
# arr = arr.reshape((shape))                   # equivalent statement
arr = np.reshape(arr, (2, 5))                  # change the shape of our data np.reshape(array, output_shape)
print(f'as long as the new shape is divisible by the number of elements, then we can reshape it! We want from shape (10) to {arr.shape}')

as long as the new shape is divisible by the number of elements, then we can reshape it! We want from shape (10) to (2, 5)


In [134]:
arr_3d = np.arange(2*3*3).reshape((2, 3, 3))
arr_2d = np.reshape(arr_3d, (2, -1))
print(f'arr_3d:\n{arr_3d}')
print(f'arr_2d:\n{arr_2d}')
print(f'{arr_3d.shape} turned into {arr_2d.shape}')

arr_3d:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
arr_2d:
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]]
(2, 3, 3) turned into (2, 9)


#### Operations and functions (addition, subtraction, etc)
Instead of iterating through a two arrays to do element by element operations, we use NumPy functions

In [135]:
arr1 = np.arange(10)
arr2 = np.ones(10)

#### Indexing, slicing

#### Broadcasting
This is the operation of making two different shaped arrays compatible for addition/other functions.

In [ ]:
arr_2d = np.ones((5, 5))


In [ ]:
# tuple1[0] = 10
# print(tuple1)
# arr = np.array(list1)  # one example of numpy array instance
# print(type(arr))
# if isinstance(arr, np.ndarray):  # checks if the object is the correct type
#     print('True!')

# example 2
# listnames = [['Danny', 26], ['Dannt', 56], ['Dannl', 15], ['Dannu', 31]]  # lists are good when we mix types
#
# arr2 = np.array(np.array(listnames, dtype=str)[:, 1], dtype=np.int16)  # dtype=np.int16
# # print(arr2)
# mean = np.mean(arr2, dtype=int)
# print(mean)

# example 3
# arr1 = np.arange(0, 1000, 0.9)
# print(arr1)
# print(arr1.ndim)  # = 1
# arr2 = np.linspace(0, 1000, 20)
# print(arr2)
# arr2 = np.reshape(arr2, (2, 2, 5))  # shape is the size of the dimension
# # arr2 = arr2.reshape((, 1))  # alternative way
# print(arr2.shape)  # 4 by 5 matrix
# print(arr2.ndim)  # could be 2
# list1 = [0, 1, 2, 3...]  -> [[0], [1], [2], ...
# arr1.ndim = 1, arr1.shape
# arr3 = [[0],
#         [1],
#         [3]]
# # dcm_data[slc, row, col] =

# arr4 = np.array([[[256]]])
# print(arr4.ndim)
# print(arr4.shape)
# print(arr4)

arr5 = 1*np.linspace(2, 100, 18).reshape((3, 2, 3))
print(arr5)
arr6 = 2*np.ones((3, 2)).reshape((3, 2, 1))
arr7 = arr5 * arr6
print(arr7)